DarkRP.defineChatCommand("help", function(ply, args)
	ply:ChatPrint("Useful commands:")
	ply:ChatPrint("/help to print this message.")
	ply:ChatPrint("/bored if you are bored.")
	ply:ChatPrint("/rules to read the OOC rules.")
	ply:ChatPrint("/laws to read the IC laws.")
	ply:ChatPrint("/slang to learn what stuff means.")
end)

DarkRP.defineChatCommand("bored", function(ply, args)
	ply:ChatPrint("Things to do when bored:")
	ply:ChatPrint("Start a war against the government.")
	ply:ChatPrint("Start a drug cartel.")
	ply:ChatPrint("Raid the police department.")
	ply:ChatPrint("Become a private investigator.")
	ply:ChatPrint("Secretly work for the police.")
end)

DarkRP.defineChatCommand("rules", function(ply, args)
	ply:ChatPrint("Rules:")
	ply:ChatPrint("Violation of these rules is subject to immediate and OOC punishment.")
	ply:ChatPrint("1. Police must always follow all laws.")
	ply:ChatPrint("2. All bases must be raidable.")
	ply:ChatPrint("3. Kill only through ways intended.")
end)

DarkRP.defineChatCommand("laws", function(ply, args)
	ply:ChatPrint("Default laws:")
	ply:ChatPrint("Violation of these laws may be subject to IC punishment, if caught.")
	ply:ChatPrint("1. Do not attack other citizens except in self defense.")
	ply:ChatPrint("2. Do not break into people's homes or bases.")
	ply:ChatPrint("3. Money printers and drugs are illegal.")
end)

DarkRP.defineChatCommand("slang", function(ply, args)
	ply:ChatPrint("Slang terms:")
	ply:ChatPrint("RDM - The act of murder without reason.")
	ply:ChatPrint("CDM - The act of murder using a vehicle.")
	ply:ChatPrint("OOC - Out Of Character.")
	ply:ChatPrint("IC - In Character.")
	ply:ChatPrint("NLR - New Life Rule.")
	ply:ChatPrint("FGM - Fair Game Rules.")
end)
